name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement"]

assignees:
  - ranodmusert

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to see.
      placeholder: Tell us what you would like to see!
      value: "A new feature!"
    validations:
      required: true
